const dataSelectOptionsKotaDanProvinsi = [
	{ value: 'Jawa Barat', label: 'Jawa Barat' },
	{ value: 'Jawa Timur', label: 'Jawa Timur' },
	{ value: 'Jawa Tengah', label: 'Jawa Tengah' },
	{ value: 'Jawa Utara', label: 'Jawa Utara' },
	{ value: 'Banten', label: 'Banten' },
	{ value: 'DKI Jakarta', label: 'DKI Jakarta' },
	{ value: 'Sumatera Utara', label: 'Sumatera Utara' },
	{ value: 'Sumatera Barat', label: 'Sumatera Barat' },
	{ value: 'Sumatera Selatan', label: 'Sumatera Selatan' },
	{ value: 'Kalimantan Barat', label: 'Kalimantan Barat' },
	{ value: 'Kalimantan Timur', label: 'Kalimantan Timur' },
	{ value: 'Kalimantan Selatan', label: 'Kalimantan Selatan' },
	{ value: 'Kalimantan Tengah', label: 'Kalimantan Tengah' },
	{ value: 'Kalimantan Utara', label: 'Kalimantan Utara' },
	{ value: 'Sulawesi Utara', label: 'Sulawesi Utara' },
	{ value: 'Sulawesi Barat', label: 'Sulawesi Barat' },
	{ value: 'Sulawesi Tengah', label: 'Sulawesi Tengah' },
	{ value: 'Sulawesi Selatan', label: 'Sulawesi Selatan' },
	{ value: 'Sulawesi Tenggara', label: 'Sulawesi Tenggara' },
	{ value: 'Gorontalo', label: 'Gorontalo' },
	{ value: 'Sulawesi Barat', label: 'Sulawesi Barat' },
	{ value: 'Maluku', label: 'Maluku' },
	{ value: 'Maluku Utara', label: 'Maluku Utara' },
	{ value: 'Papua', label: 'Papua' },
	{ value: 'Papua Barat', label: 'Papua Barat' },
	{ value: 'Papua', label: 'Papua' },
	{ value: 'Bali', label: 'Bali' },
	{ value: 'Nusa Tenggara Barat', label: 'Nusa Tenggara Barat' },
	{ value: 'Nusa Tenggara Timur', label: 'Nusa Tenggara Timur' },
	{ value: 'Riau', label: 'Riau' },
	{ value: 'Bangka Belitung', label: 'Bangka Belitung' },
	{ value: 'Kepulauan Riau', label: 'Kepulauan Riau' },
	{ value: 'Lampung', label: 'Lampung' },
]

export default dataSelectOptionsKotaDanProvinsi